### ISSUE TITLE
Mockups of every page

### ISSUE THREAD

**Issue by mattkim009** [LoveMilkTeaDevs/Dev_Repo#1]
Do all work for this task in a branch called issue-<27>
[Whimsical](https://whimsical.com)

## Subtasks
- [x] Login Page
- [x] Map Homescreen
     - Map Zoom
     - Map "Guidance"
- [ ] Store List page
- [ ] Venmo/Instagram-like Photo Feed
- [ ] Store page
- [ ] Store Photo Feed
- [ ] People's Review Page
- [ ] Review form field
- [ ] Settings Page
      - [ ] Settings Icon on every page
